import React, { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Github, Linkedin, Menu, X } from 'lucide-react';

const experiences = [
  { id:'cibc', company:'CIBC', role:'TechOps & Support Intern', date:'May 2026 — Present', location:'Toronto, ON', bullets:['Developing and supporting scheduling platforms within Enterprise Technology Services, improving reliability through automation and system enhancements.','Troubleshooting production issues across Linux/Unix distributed environments using ServiceNow and GitHub to manage incidents and changes.'] },
  { id:'course', company:'University of Alberta', tabLabel:'Course Dev @ U of A', role:'Course Developer · CMPUT 393', date:'Aug 2026 — Present', location:'Remote', bullets:['Designing the curriculum for Scalable Data-Intensive Analytics around core distributed-systems concepts and Designing Data-Intensive Applications.','Creating hands-on labs and a semester-long, Google Analytics-inspired project for building and evaluating scalable analytics systems.'] },
  { id:'muchlearning', company:'MuchLearning', role:'Software Developer Intern', date:'Jan 2026 — Apr 2026', location:'Edmonton, AB', bullets:['Built FastAPI microservices for high-throughput production data pipelines in an Agile team environment.','Designed scalable, fault-tolerant REST APIs that improved system reliability and automated decision workflows.'] },
  { id:'ur2phd', company:'UR2PhD', role:'Research Scholar', date:'Sep 2025 — Dec 2025', location:'Edmonton, AB', bullets:['Designed scalable experimentation pipelines to evaluate performance, scalability, and failure modes.','Engineered Python/C++ benchmarking tools measuring latency, throughput, and reliability at scale.'] },
  { id:'daylily', company:'Daylily AI', role:'Full Stack Developer Intern', date:'Aug 2025 — Dec 2025', location:'Remote', bullets:['Built React and FastAPI systems that integrated AI-powered features into production user workflows.','Designed REST APIs, implemented frontend components, and deployed features through the complete SDLC.'] },
  { id:'iit', company:'IIT Goa', role:'Research Intern', date:'May 2025 — Jul 2025', location:'Goa, India', bullets:['Developed three data-driven control algorithms for flow battery management, reducing energy loss by 25%.','Contributed to research on programmable flow systems targeting future IEEE publication.'] },
  { id:'ta', company:'University of Alberta', tabLabel:'Teaching Assistant @ U of A', role:'Teaching Assistant', date:'Jan 2025 — Apr 2026', location:'Edmonton, AB', bullets:['Graded 700+ assignments and led 35 labs, communicating complex technical concepts to diverse students.','Reduced grading turnaround from four days to 1.5 days with Python automation scripts.'] },
];

const projects = [
  { number:'01', slug:'liquidity', title:'Information Disclosure & Intraday Liquidity Risk', date:'DEC 2025', description:'A technical study of how intraday liquidity disclosure changes risk during payment disruptions, supported by computational simulations across transaction workloads.', tech:['Python','NumPy','Matplotlib'], category:'Research / Simulation' },
  { number:'02', slug:'signal', title:'Signal Vault', date:'MAY — NOV 2025', description:'An offline-first search system for emergency access during outages. It keeps 100+ terms available locally and delivers 90% faster search through measured caching optimizations.', tech:['Python','JavaScript','Node.js','localStorage'], category:'Offline-first / Web', githubUrl:'https://github.com/guneettt/signal-vault' },
  { number:'03', slug:'bias', title:'Bias Visualizer', date:'MAY 2025', description:'A Chrome extension comparing 30+ trending terms across Google Trends and Reddit, backed by a real-time FastAPI text-analysis service sustaining 500+ queries per second.', tech:['JavaScript','Chrome API','FastAPI','Python'], category:'Browser extension / Data', githubUrl:'https://github.com/guneettt/bias-visualizer' },
  { number:'04', slug:'swc', title:'SWC Automotive Platform', date:'CLIENT PROJECT', description:'A responsive automotive business platform with 15+ dynamic pages for inventory, services, and lead capture, plus a Firebase-backed CMS for real-time content updates.', tech:['React','Tailwind CSS','Firebase'], category:'Web / CMS' },
  { number:'05', slug:'ray', title:'Photorealistic 3D Ray Tracer', date:'COMPUTER GRAPHICS', description:'A ray tracing engine written from scratch in C with multiple geometric primitives, realistic lighting, optimized ray–object intersections, and clean Makefile builds.', tech:['C','Makefile','Linear Algebra','Graphics'], category:'Rendering / Systems' },
  { number:'06', slug:'tweets', title:'Scalable Tweet Analytics Engine', date:'DATA SYSTEMS', description:'A high-throughput analytics system using MongoDB and Python, with custom schemas and batch-processing pipelines for efficient filtering and aggregation.', tech:['Python','MongoDB','SQL','JSON'], category:'Analytics / Data' },
  { number:'07', slug:'trustline', title:'TrustLine — AI Fraud Detection', date:'1ST PLACE · $6K', description:'An award-winning mobile app that detects deepfake scam calls in real time, designed to make fraud protection more accessible to older adults and caregivers.', tech:['React Native','FastAPI','Machine Learning','Audio'], category:'AI / Mobile', githubUrl:'https://github.com/WanderingWalnut/Trustline' },
  { number:'08', slug:'ridesafe', title:'RideSafe — Transit Safety', date:'2ND PLACE · $1K', description:'A real-time transit safety app using Vision Transformer threat detection to monitor live video and trigger alerts, built as a rapid DevCon proof of concept.', tech:['React Native','Flask','Computer Vision','Python'], category:'Vision / Mobile', githubUrl:'https://github.com/mikejattu/RideSafe' },
  { number:'09', slug:'whimsy', title:'Whimsy', date:'GROUP PROJECT', description:'A collaborative Android social app with mood-based posts, comments, real-time emotional feeds, privacy-aware following, an interactive mood map, and DALL·E imagery.', tech:['Java','Android Studio','Firebase','DALL·E API'], category:'Social / Android' },
];
const navigation = [['about','About'],['experience','Experience'],['work','Projects'],['contact','Contact']];

function ProjectVisual({ type }) {
  if (type === 'liquidity') return <div className="project-visual liquidity-visual" aria-hidden="true"><div className="visual-top"><span>LIQUIDITY / RISK</span><span>SIM_04</span></div><div className="chart-grid"><div className="chart-line"/><div className="chart-line line-b"/><span className="chart-label">NORMAL</span><span className="chart-label risk">DISRUPTION</span></div><div className="visual-bottom"><span>Δ 18.42%</span><span>RUN COMPLETE</span></div></div>;
  if (type === 'signal') return <div className="project-visual signal-visual" aria-hidden="true"><div className="signal-rings"><span/><span/><span/></div><div className="signal-terminal"><span>&gt; status: offline</span><strong>VAULT READY_</strong><span>100+ records cached</span></div><div className="signal-badge">NO NETWORK REQUIRED</div></div>;
  if (type === 'bias') return <div className="project-visual bias-visual" aria-hidden="true"><div className="visual-top"><span>TREND COMPARISON</span><span>LIVE</span></div><div className="bias-bars">{[70,42,88,58,76].map((height,index)=><div className="bias-column" key={height}><span style={{height:`${height}%`}}/><i style={{height:`${100-height/2}%`}}/><small>0{index+1}</small></div>)}</div><div className="bias-key"><span>GOOGLE</span><span>REDDIT</span></div></div>;
  const visualLabels = { swc:['INVENTORY','CMS / LIVE'], ray:['RAY TRACE','FRAME 0042'], tweets:['DATA FLOW','BATCH / 08'], trustline:['VOICE SCAN','RISK: LOW'], ridesafe:['VISION FEED','MONITORING'], whimsy:['MOOD MAP','FEELING: :)'] };
  const [label,status] = visualLabels[type];
  return <div className={`project-visual abstract-visual ${type}-visual`} aria-hidden="true"><div className="visual-top"><span>{label}</span><span>{status}</span></div><div className="abstract-orbit"><span/><span/><i/></div><strong>{type.toUpperCase()}</strong><div className="visual-bottom"><span>PROJECT / {type.toUpperCase()}</span><span>09.26</span></div></div>;
}

export default function App() {
  const [menuOpen,setMenuOpen]=useState(false);
  const [activeExperience,setActiveExperience]=useState(experiences[0].id);
  const activeJob=experiences.find(job=>job.id===activeExperience);
  useEffect(()=>{const close=()=>window.innerWidth>=768&&setMenuOpen(false);window.addEventListener('resize',close);return()=>window.removeEventListener('resize',close)},[]);
  return <div className="site-shell">
    <nav className="topbar"><a className="wordmark" href="#home" aria-label="Guneet Kaur, home">GK<span>/26</span></a>
      <div className="desktop-nav">{navigation.map(([id,label],index)=><a href={`#${id}`} key={id}><span>0{index+1}</span>{label}</a>)}<a className="resume-link" href="/resume.pdf" target="_blank" rel="noreferrer">Résumé <ArrowUpRight size={15}/></a></div>
      <button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button>
      {menuOpen&&<div className="mobile-nav">{navigation.map(([id,label])=><a href={`#${id}`} onClick={()=>setMenuOpen(false)} key={id}>{label}</a>)}<a href="/resume.pdf" target="_blank" rel="noreferrer">Résumé ↗</a></div>}
    </nav>
    <main>
      <section className="hero" id="home"><p className="eyebrow">HELLO — I’M GUNEET KAUR</p><h1>I build software<br/>for the <em>real world.</em></h1><div className="hero-lower"><p>Computer Science student and developer working across distributed systems, data, research, and thoughtful digital experiences.</p><a href="#work">EXPLORE MY WORK <ArrowDownRight/></a></div><div className="hero-meta"><span>CS @ UNIVERSITY OF ALBERTA</span></div></section>
      <section className="section about" id="about"><header className="section-header"><span>01 / ABOUT</span><p>A little context</p></header><div className="about-grid"><h2>Curious about the space where <span>systems</span>, <span>people</span>, and <span>useful products</span> meet.</h2><div className="about-copy"><p>I’m a Computer Science undergraduate at the University of Alberta, graduating in December 2027. I like turning complicated problems into software that feels understandable and dependable.</p><p>My work has moved between enterprise infrastructure, scalable data systems, AI-enabled products, research, and teaching. That range keeps me asking both “does it work?” and “does it matter?”</p><div className="skill-cloud">{['Python','Java','JavaScript','TypeScript','C / C++','SQL','React','FastAPI','Docker','Azure','Linux / Unix','REST APIs'].map(skill=><span key={skill}>{skill}</span>)}</div></div></div></section>
      <section className="section experience" id="experience"><header className="section-header"><span>02 / EXPERIENCE</span><p>Where I’ve contributed</p></header><div className="experience-layout"><div className="experience-list" role="tablist">{experiences.map((job,index)=><button className={activeExperience===job.id?'active':''} onClick={()=>setActiveExperience(job.id)} key={job.id} role="tab"><span>{String(index+1).padStart(2,'0')}</span><strong>{job.tabLabel || job.company}</strong><small>{job.date.split(' — ')[0]}</small></button>)}</div><article className="experience-detail"><div className="detail-meta"><span>{activeJob.date}</span><span>{activeJob.location}</span></div><h3>{activeJob.role}</h3><p className="company">@ {activeJob.company}</p><ul>{activeJob.bullets.map(bullet=><li key={bullet}>{bullet}</li>)}</ul></article></div></section>
      <section className="section projects" id="work"><header className="section-header"><span>03 / ALL PROJECTS</span><p>Experiments turned tangible</p></header><div className="projects-intro"><h2>Things I’ve<br/><em>made & measured.</em></h2><p>A growing collection spanning research, resilient software, data systems, AI, mobile, and the web.</p></div><div className="project-grid">{projects.map(project=><article className="project-card" key={project.title}><ProjectVisual type={project.slug}/><div className="project-content"><div className="project-kicker"><span>{project.number} / {project.category}</span><span>{project.date}</span></div><div className="project-title-row"><h3>{project.title}</h3>{project.githubUrl&&<a href={project.githubUrl} target="_blank" rel="noreferrer" aria-label={`${project.title} on GitHub`}><Github/></a>}</div><p>{project.description}</p><div className="project-tech">{project.tech.map(tech=><span key={tech}>{tech}</span>)}</div></div></article>)}</div></section>
      <section className="section contact" id="contact"><span className="contact-index">04 / CONTACT</span><p>HAVE AN IDEA, OPPORTUNITY, OR JUST WANT TO SAY HI?</p><a href="mailto:guneet4@ualberta.ca">Let’s talk.<ArrowUpRight/></a><div className="contact-links"><a href="https://github.com/guneettt" target="_blank" rel="noreferrer"><Github/> GitHub</a><a href="https://www.linkedin.com/in/itsguneettt" target="_blank" rel="noreferrer"><Linkedin/> LinkedIn</a><span>guneet4@ualberta.ca</span></div></section>
    </main><footer><span>© {new Date().getFullYear()} GUNEET KAUR</span><span>DESIGNED + BUILT WITH INTENTION</span></footer>
  </div>;
}
